### ISSUE TITLE
Looks good but...

### ISSUE THREAD

**Issue by adrianvintu** [elrizwiraswara/flutter_steps#1]
Why are the steps not widgets? (instead of string title/description)

This reduces the use cases to a minimum.

**Comment by elrizwiraswara** [comment]
I used strings for the title and description because they have active and inactive states (e.g., colors) that need to be controlled. Using widgets would make it harder to manage these states uniformly across steps. However, since the title and description are optional, you can still use the leading widget to add custom text widgets if needed.

**Comment by adrianvintu** [comment]
I needed specific positioning for the widgets. In the end I ended up using another component, and manually customizing it.
